In [1]:
import numpy as np

vec = np.array([1,2,3,4,5,6])
print(vec)

print('Shape of vec:', vec.shape)
print('Size of vec:', vec.size)
print('Dimension of vec:', vec.ndim)

[1 2 3 4 5 6]
Shape of vec: (6,)
Size of vec: 6
Dimension of vec: 1


In [2]:
# reshape the existing vector into a SxF matrix
y = vec.reshape(6, 1)
print('y:', y)
print('Shape of y:', y.shape)
print('Size of y:', y.size)
print('Dimension of y:', y.ndim)

y: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Shape of y: (6, 1)
Size of y: 6
Dimension of y: 2


In [42]:
# Test several operations
a = vec.reshape(-1, 1)
b = vec.reshape(1, -1)
c = vec.reshape(2, 3)
d = vec.reshape(-1, 3)
# e = vec.reshape(-1, -1)   ValueError: can only specify one unknown dimension
e = vec[..., np.newaxis]
f = c[:, np.newaxis]
g = c[np.newaxis, :, :]
h = c[np.newaxis, ...]
i = np.dot(vec, vec)
j = vec @ vec
k = vec.T
l = a.T
# m = np.dot(a, vec)        ValueError: shapes (6,1) and (6,) not aligned: 1 (dim 1) != 6 (dim 0)
# n = c @ d                 ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [43]:
print("a", a)
print("b", b, b.shape)
print("c", c, c.shape)
print("d", d, d.shape)
print("e", e, e.shape)
print("f", f, f.shape)
print("g", g, g.shape)
print("h", h, h.shape)
print("i", i)
print("j", j)
print("k", k)
print("l", l)

a [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
b [[1 2 3 4 5 6]] (1, 6)
c [[1 2 3]
 [4 5 6]] (2, 3)
d [[1 2 3]
 [4 5 6]] (2, 3)
e [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
f [[[1 2 3]]

 [[4 5 6]]] (2, 1, 3)
g [[[1 2 3]
  [4 5 6]]] (1, 2, 3)
h [[[1 2 3]
  [4 5 6]]] (1, 2, 3)
i 91
j 91
k [1 2 3 4 5 6]
l [[1 2 3 4 5 6]]
