In [1]:
import numpy as np

vec = np.array([1,2,3,4,5,6])
print(vec)

print('Shape of vec:', vec.shape)
print('Size of vec:', vec.size)
print('Dimension of vec:', vec.ndim)

[1 2 3 4 5 6]
Shape of vec: (6,)
Size of vec: 6
Dimension of vec: 1


In [2]:
# reshape the existing vector into a SxF matrix
y = vec.reshape(6, 1)
print('y:', y)
print('Shape of y:', y.shape)
print('Size of y:', y.size)
print('Dimension of y:', y.ndim)

y: [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
Shape of y: (6, 1)
Size of y: 6
Dimension of y: 2


In [55]:
# Test several operations
a = vec.reshape(-1, 1)
b = vec.reshape(1, -1)
c = vec.reshape(2, 3)
d = vec.reshape(-1, 3)
# e = vec.reshape(-1, -1)   ValueError: can only specify one unknown dimension
e = vec[..., np.newaxis]
f = c[:, np.newaxis]
g = c[np.newaxis, :, :]
h = c[np.newaxis, ...]
i = np.dot(vec, vec)
j = vec @ vec
k = vec.T
l = a.T
# m = np.dot(a, vec)        ValueError: shapes (6,1) and (6,) not aligned: 1 (dim 1) != 6 (dim 0)
# n = c @ d                 ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
o = c.T @ d
p = c @ d.T
q = c @ d.T @ c
r = np.dot(c, d.T)
s = np.matmul(c, d.T)
t = np.dot(c, 4)
u = np.dot(4, c)
v = 4*c

In [56]:
print("a", a)
print("b", b, b.shape)
print("c", c, c.shape)
print("d", d, d.shape)
print("e", e, e.shape)
print("f", f, f.shape)
print("g", g, g.shape)
print("h", h, h.shape)
print("i", i)
print("j", j)
print("k", k)
print("l", l)
print("o", o)
print("p", p)
print("q", q)
print("r", r)
print("s", s)
print("t", t)
print("u", u)
print("v", v)

a [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
b [[1 2 3 4 5 6]] (1, 6)
c [[1 2 3]
 [4 5 6]] (2, 3)
d [[1 2 3]
 [4 5 6]] (2, 3)
e [[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
f [[[1 2 3]]

 [[4 5 6]]] (2, 1, 3)
g [[[1 2 3]
  [4 5 6]]] (1, 2, 3)
h [[[1 2 3]
  [4 5 6]]] (1, 2, 3)
i 91
j 91
k [1 2 3 4 5 6]
l [[1 2 3 4 5 6]]
o [[17 22 27]
 [22 29 36]
 [27 36 45]]
p [[14 32]
 [32 77]]
q [[142 188 234]
 [340 449 558]]
r [[14 32]
 [32 77]]
s [[14 32]
 [32 77]]
t [[ 4  8 12]
 [16 20 24]]
u [[ 4  8 12]
 [16 20 24]]
v [[ 4  8 12]
 [16 20 24]]


In [64]:
# Creating arrays
aa = np.zeros((2, 3))
ab = np.zeros_like(c)
ac = np.ones((4, 4))
ad = np.eye(3)
ae = np.arange(0, 10, 2)
af = range(0, 10, 2)

print(aa)
print(ab)
print(ac)
print(ad)
print("ae", ae, type(ae))
print("af", af)

[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
ae [0 2 4 6 8] <class 'numpy.ndarray'>
af range(0, 10, 2)
